# Generated by Django 5.2.12 on 2026-04-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0002_financialrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('analyst', 'Analyst'), ('admin', 'Admin')], default='viewer', max_length=20),
        ),
    ]
